export enum HttpStatus {
  OK = 200, // OK
  CREATED = 201, // CREATED
  NO_CONTENT = 204, // NO CONTENT
  BAD_REQUEST = 400, // DADO RUIM OU FALTANTE NO SERVIDOR
  UNAUTHORIZED = 401, // NÃO AUTORIZADO
  FORBIDDEN = 403, // PROIBIDO
  NOT_FOUND = 404, // NÃO ENCONTRADO
  UNPROCESSABLE_ENTITY = 422, // NÃO É POSSÍVEL PROCESSAR A INSTRUÇÃO PRESENTE
  SERVER_ERROR = 500, // ERRO DESCONHECIDO NO SERVIDOR
}
